import TimBaseManager from "./manager/timBaseManager";
import TimGroupManager from "./manager/timGroupManager";

const APIS =  [
    {
        manager:"timBaseManager",
        method:[
            {
                name:"init",
                action:(callback)=>{
                    TimBaseManager.TIMInit().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"login",
                action:(callback)=>{
                    TimBaseManager.TIMLogin().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"uninit",
                action:(callback)=>{
                    TimBaseManager.uninit().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getServerTime",
                action:(callback)=>{
                    TimBaseManager.getServerTime().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getSDKVersion",
                action:(callback)=>{
                    TimBaseManager.getSDKVersion().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"logout",
                action:(callback)=>{
                    TimBaseManager.logout().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getLoginStatus",
                action:(callback)=>{
                    TimBaseManager.getLoginStatus().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getLoginUserID",
                action:(callback)=>{
                    TimBaseManager.getLoginUserID().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            
        ]
    },
    {
        manager:"groupManager",
        method:[
            {
                name:"createGroup",
                action:(callback)=>{
                    TimGroupManager.createGroup().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name: "deleteGroup",
                action:(callback)=>{
                    TimGroupManager.deleteGroup().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name: "getJoinedGroup",
                action:(callback)=>{
                    TimGroupManager.getJoinedGroupList().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name: "getGroupInfoList",
                action:(callback)=>{
                    TimGroupManager.getGroupInfoList().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name: "modifyGroupInfo",
                action:(callback)=>{
                    TimGroupManager.modifyGroupInfo().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name: "getGroupMemberInfoList",
                action:(callback)=>{
                    TimGroupManager.getGroupMemberInfoList().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name: "modifyGroupMemberInfo",
                action:(callback)=>{
                    TimGroupManager.modifyGroupMemberInfo().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name: "getGroupPendencyList",
                action:(callback)=>{
                    TimGroupManager.getGroupPendencyList().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            }
        ]
    },
]
export default APIS;