import ConversationManager from "./manager/conversationManager";
import TimBaseManager from "./manager/timBaseManager";

const APIS =  [
    {
        manager:"timBaseManager",
        method:[
            {
                name:"init",
                action:(callback)=>{
                    TimBaseManager.TIMInit().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"login",
                action:(callback)=>{
                    TimBaseManager.TIMLogin().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"uninit",
                action:(callback)=>{
                    TimBaseManager.uninit().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getServerTime",
                action:(callback)=>{
                    TimBaseManager.getServerTime().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getSDKVersion",
                action:(callback)=>{
                    TimBaseManager.getSDKVersion().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"logout",
                action:(callback)=>{
                    TimBaseManager.logout().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getLoginStatus",
                action:(callback)=>{
                    TimBaseManager.getLoginStatus().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"getLoginUserID",
                action:(callback)=>{
                    TimBaseManager.getLoginUserID().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
            {
                name:"setNetworkStatusListenerCallback",
                action:(callback)=>{
                    TimBaseManager.setNetworkStatusListenerCallback().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            },
        ]
    },
    {
        manager: 'conversationManager',
        method:[
            {
                name:"TIMSetConvEventCallback",
                action:(callback)=>{
                    try{
                        ConversationManager.TIMSetConvEventCallback().then(data=>{
                            callback(JSON.stringify(data))
                        }).catch(err=>{
                            console.log(err)
                            callback('12312')
                        })
                    }catch(err){
                        console.log(err)
                    }
                }
            },
        ]
    },
    {
        manager:"groupManager",
        method:[
            {
                name:"createGroup",
                action:(callback)=>{
                    TimBaseManager.TIMLogin().then(data=>{
                        callback(JSON.stringify(data))
                    }).catch(err=>{
                        callback(err.toString())
                    })
                }
            }
        ]
    },
]
export default APIS;